Make Inbound and Outbound Anomaly Score optinal
since ANOMALYIN and ANOMALYOUT where not optional the script failed if they are not set.
The docker image started as expected, but the options are not applied.

Error message:
Traceback (most recent call last):
File "<stdin>", line 3, in <module>
File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'ANOMALYIN'